---

- name: Create a temporary file to hold import config.
  become: true
  ansible.builtin.tempfile:
    state: file
    suffix: import
  register: ansible_role_hpe_isut_import_config
  changed_when: false
  when: ansible_role_hpe_isut_config_needs_patching.changed

- name: Create import configuration.
  become: true
  ansible.builtin.template:
    src: hpe_isut_config.j2
    dest: "{{ ansible_role_hpe_isut_import_config.path }}"
    group: root
    owner: root
    mode: '0600'
  when: ansible_role_hpe_isut_config_needs_patching.changed

- name: Import iSUT configuration from template.
  become: true
  ansible.builtin.command:
    cmd: "{{ ansible_role_hpe_isut_bin }} -importconfig {{ ansible_role_hpe_isut_import_config.path }}"

- name: Remove temporary files.
  become: true
  ansible.builtin.file:
    path: "{{ ansible_role_hpe_isut_import_config.path }}"
    state: absent
