---

- name: Install HPE iSUT packages.
  become: true
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
    update_cache: true
    lock_timeout: 300
  loop: "{{ ansible_role_hpe_isut_packages }}"
